### ISSUE TITLE
The file pre can't be opened

### ISSUE THREAD

**Issue by HorticLee** [Menggg/BLINK#10]
Hi, when I used BLINK (blink_linux) to test the **demo data**, **blink_linux --gwas --file myData --numeric**, there was an error as follows:

**************************
*       BLINK v0.01 start       *
**************************
****************************************************************
*   BLINK is written by Meng Huang and designed by Zhiwu Zhang  *
*       Please visit zzlab.net to get more information about BLINK      *
****************************************************************

Input arguments:   --file myData --out blink --numeric
 --gwas

one cycle include 1000 SNPs inside!

The number of marker = 3093
number of individual is 281
number of marker is 3093
**The file pre can't be opened!**
All the time consumption = 0 seconds

Thanks!

**Comment by dosshra** [comment]
Hello!
I get the same results with the last version.

**Comment by dosshra** [comment]
As for 28/08/24 the binaries were updated. Now the numeric demo runs OK. Thank you Meng for the fix.
